

function ProductComponents(){
    const productList = [
        "Rice",
        "Bread",
        "Milk",
        "Eggs",
        "Butter",
        "Cheese",
        "Chicken",
        "Beef",
        "Fish",
        "Vegetables",
        "Fruits",
        "Pasta",
        "Cereal",
        "Flour",
        "Sugar",
        "Salt",
        "Pepper",
        "Olive Oil",
        "Cooking Oil",
        "Coffee",
        "Tea",
        "Juice",
        "Yogurt",
        "Beans",
        "Lentils",
        "Potatoes",
        "Onions",
        "Garlic",
        "Tomatoes",
        "Carrots",
        "Peppers",
        "Spinach",
        "Broccoli",
        "Apples",
        "Bananas",
        "Oranges",
        "Berries",
        "Lettuce",
        "Cucumbers",
        "Zucchini",
        "Mushrooms",
        "Herbs",
        "Spices",
        "Bread",
        "Tortillas",
        "Crackers",
        "Nuts",
        "Seeds",
        "Snacks",
        "Chips",
        "Chocolate",
        "Ice Cream",
        "Frozen Vegetables",
        "Frozen Fruits",
        "Canned Vegetables",
        "Canned Fruits",
        "Soup",
        "Broth",
        "Tomato Sauce",
        "Pasta Sauce",
        "Ketchup",
        "Mustard",
        "Mayonnaise",
        "Vinegar",
        "Soy Sauce",
        "Hot Sauce",
        "Honey",
        "Jam",
        "Peanut Butter",
        "Baking Powder",
        "Baking Soda",
        "Yeast",
        "Dish Soap",
        "Laundry Detergent",
        "Toilet Paper",
        "Paper Towels",
        "Tissues",
        "Trash Bags",
        "Aluminum Foil",
        "Plastic Wrap",
        "Ziploc Bags",
        "Cleaning Supplies",
        "Hand Soap",
        "Shampoo",
        "Conditioner",
        "Toothpaste",
        "Toothbrushes",
        "Deodorant",
        "Body Wash",
        "Razors",
        "Shaving Cream"
    ];

    return (
        <>
            <ul>
                <li>
                    {productList.map((products) => <li>{products}</li>)}
                </li>
            </ul>
        </>
    );
}

export default ProductComponents;